config:configure webpack
was-coder/book-library pull request #4
Opened 2022-04-18 06:20 UTC by was-coder

This PR:
- Configure webpack
- Use Single Page Application

2022-12-18 13:08 UTC, adejam requested changes
## Needs little improvements before merging

In addition to the code reviews, some UI issues were spotted.

- In the add book page, when a book is added, the page is reloaded and a user goes back to the add book page the page loads with the list of books and also the message `Book List is empty... Please add a book`...
- In addition to the above, when the page is still loading there is not loading indication that a result should be expected before the user gets their books when a user has existing books in the local storage or displays `Book List is empty... Please add a book` when there is none. This can be seen as a solution to the above issue
- Another issue is that the table list head is currently having a pointer cursor, this is the same with the message `Book List is empty... Please add a book`. It passes the wrong message that they are clickable when they are not
- Also after initially adding books and then removing all books, the user doesn't get the message/layout `Book List is empty... Please add a book`
- Also for privacy reasons, let's remove our real address as it is not needed here(also for privacy reasons)


Please let's make the following changes

2022-12-18 13:08 UTC, adejam commented on src/css/large_screen.css
> +  width: 100%;
These css classes can be made into one or combined like

```css
.update-btn, .edit-input {
  width: 100%;
}
```

2022-12-18 13:08 UTC, adejam commented on src/css/main.css
> +  justify-content: center;
This properties are repeated in many places

2022-12-18 13:08 UTC, adejam commented on src/js/functionality/popup/addPopUp.js
> +  main.appendChild(func(getBook));
calling a function as an argument of another function is not ideal. It would be ok to pass the initial function call to a variable and then pass that as an argument to the `appendChild` function

2022-12-18 13:08 UTC, adejam commented on src/js/pages/bookList.js
> +      cell.style.color = '#e8e8f0';
This seems a little verbose, what  is the advantage of using this instead of a class

2022-12-25 15:49 UTC, adejam commented
# LGTM

All good now, Please merge. 

Goodluck on your next milestone or project is it

2022-12-25 15:54 UTC, was-coder commented on src/css/large_screen.css
> +  width: 100%;
Thanks. I have resolved it

2022-12-25 15:54 UTC, was-coder commented on src/css/main.css
> +  justify-content: center;
I have worked on all the redundancy

2022-12-25 15:54 UTC, was-coder commented on src/js/functionality/popup/addPopUp.js
> +  main.appendChild(func(getBook));
I have made changes to it. Thanks

2022-12-25 15:55 UTC, was-coder commented on src/js/pages/bookList.js
> +      cell.style.color = '#e8e8f0';
Thanks. Solved

2022-12-25 15:56 UTC, merged